USE autoclub;
DROP FUNCTION IF EXISTS NZ;
DELIMITER $$
CREATE FUNCTION NZ(TestValue VARCHAR(255), NullValue VARCHAR(255) ) RETURNS VARCHAR(255)
no sql

BEGIN
    
    RETURN COALESCE(TestValue,NullValue);   
    
END $$
DELIMITER ;
