USE autoclub;

DROP FUNCTION IF EXISTS fn_Lookup;
DELIMITER $$
CREATE FUNCTION fn_Lookup(LookupKey VARCHAR(50)) RETURNS VARCHAR (200) 
DETERMINISTIC

BEGIN

DECLARE TheValue VARCHAR(200);
SET TheValue = (SELECT `Value` FROM `lookups` WHERE `Key` = LookupKey);
RETURN (RTRIM(LTRIM(TheValue)));   

END $$
DELIMITER ;
